export const links = [
    { href: "/", label: "NFL" },
    { href: "/nba", label: "NBA" },
    { href: "/mlb", label: "MLB" },
    { href: "/nhl", label: "NHL" },
]

export const seasons = [
    { title: "Year", value: "" },
    { title: "2016", value: "2016" },
    { title: "2017", value: "2017" },
    { title: "2018", value: "2018" },
    { title: "2019", value: "2019" },
    { title: "2020", value: "2020" },
    { title: "2021", value: "2021" },
    { title: "2022", value: "2022" },
    { title: "2023", value: "2023" },
]

export const teams = [
    { value: "11", title: "Arizona Cardinals" },
    { value: "8", title: "Atlanta Falcons" },
    { value: "5", title: "Baltimore Ravens" },
    { value: "20", title: "Buffalo Bills" },
    { value: "19", title: "Carolina Panthers" },
    { value: "16", title: "Chicago Bears" },
    { value: "10", title: "Cincinnati Bengals" },
    { value: "9", title: "Cleveland Browns" },
    { value: "29", title: "Dallas Cowboys" },
    { value: "28", title: "Denver Broncos" },
    { value: "7", title: "Detroit Lions" },
    { value: "15", title: "Green Bay Packers" },
    { value: "26", title: "Houston Texans" },
    { value: "21", title: "Indianapolis Colts" },
    { value: "2", title: "Jacksonville Jaguars" },
    { value: "17", title: "Kansas City Chiefs" },
    { value: "1", title: "Las Vegas Raiders" },
    { value: "30", title: "Los Angeles Chargers" },
    { value: "31", title: "Los Angeles Rams" },
    { value: "25", title: "Miami Dolphins" },
    { value: "32", title: "Minnesota Vikings" },
    { value: "3", title: "New England Patriots" },
    { value: "4", title: "New York Giants" },
    { value: "13", title: "New York Jets" },
    { value: "27", title: "New Orleans Saints" },
    { value: "12", title: "Philadelphia Eagles" },
    { value: "22", title: "Pittsburgh Steelers" },
    { value: "14", title: "San Francisco 49ers" },
    { value: "23", title: "Seattle Seahawks" },
    { value: "24", title: "Tampa Bay Buccaneers" },
    { value: "6", title: "Tennessee Titans" },
    { value: "18", title: "Washington Commanders" },
]